/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.0.96.1 */
/* Module Version: 1.2 */
/* Wed Feb 28 10:44:46 2018 */

/* parameterized module instance */
spi_slave_efb __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .spi_clk( ), .spi_miso( ), .spi_mosi( ), .spi_scsn( ));
