INSERT INTO SlotTypes VALUES(0,'No Card in Slot');
INSERT INTO SlotTypes VALUES(1,'Card in Slot Not Programmed');
INSERT INTO SlotTypes VALUES(2,'ST Stepper');
INSERT INTO SlotTypes VALUES(3,'HC Stepper');
INSERT INTO SlotTypes VALUES(4,'Servo');
INSERT INTO SlotTypes VALUES(5,'Shutter');
INSERT INTO SlotTypes VALUES(6,'OTM DAC');
INSERT INTO SlotTypes VALUES(7,'OTM RS232');
INSERT INTO SlotTypes VALUES(8,'High-Current Stepper Card');
INSERT INTO SlotTypes VALUES(9,'Slider IO');
INSERT INTO SlotTypes VALUES(10,'Shutter 4');
INSERT INTO SlotTypes VALUES(11,'Piezo Elliptec');
INSERT INTO SlotTypes VALUES(12,'ST Invert Stepper BISS');
INSERT INTO SlotTypes VALUES(13,'ST Invert Stepper SSI');
INSERT INTO SlotTypes VALUES(14,'Piezo');
INSERT INTO SlotTypes VALUES(15,'MCM Stepper Internal BISS L6470');
INSERT INTO SlotTypes VALUES(16,'MCM Stepper Internal SSI L6470');
INSERT INTO SlotTypes VALUES(17,'MCM Stepper L6470 MicroDB15');
INSERT INTO SlotTypes VALUES(18,'Shutter 4 REV 6');
INSERT INTO SlotTypes VALUES(19,'MCM Stepper LC HD DB15');
INSERT INTO SlotTypes VALUES(20,'MCM Flipper Shutter');
INSERT INTO SlotTypes VALUES(21,'MCM Flipper Shutter (Rev A)');
INSERT INTO SlotTypes VALUES(65535,'Invalid Card Type');
