#ifndef APT_PRELUDE_H
#define APT_PRELUDE_H

#include "../apt-deprecation.h"

/****************************************************************************
 * APT Region - Prelude (0x4300 - 0x43FF)                                   *
 ****************************************************************************/
// SYS Subregion (0x4300 - 0x434F)
#define MGMSG_PREL_SYS_REQ_DATA_ENDIANNESS          APT_DEPRECATION_ERROR("deprecated") // 0x4300
#define MGMSG_PREL_SYS_GET_DATA_ENDIANNESS          APT_DEPRECATION_ERROR("deprecated") // 0x4301
#define MGMSG_PREL_SYS_SET_DATA_ENDIANNESS          APT_DEPRECATION_ERROR("deprecated") // 0x4302
#define MGMSG_PREL_SYS_REQ_CM7_VERSION              0x4303
#define MGMSG_PREL_SYS_GET_CM7_VERSION              0x4304
#define MGMSG_PREL_SYS_SET_CM7_VERSION              0x4305
#define MGMSG_PREL_SYS_REQ_CM4_VERSION              0x4306
#define MGMSG_PREL_SYS_GET_CM4_VERSION              0x4307
#define MGMSG_PREL_SYS_SET_CM4_VERSION              0x4308
#define MGMSG_PREL_SYS_REQ_UNIQUE_IDENTIFER         APT_DEPRECATION_ERROR("deprecated") // 0x4309
#define MGMSG_PREL_SYS_GET_UNIQUE_IDENTIFIER        APT_DEPRECATION_ERROR("deprecated") // 0x430A
#define MGMSG_PREL_SYS_SET_UNIQUE_IDENTIFIER        APT_DEPRECATION_ERROR("deprecated") // 0x430B
#define MGMSG_PREL_SYS_REQ_FW_UPDATE                0x430C
#define MGMSG_PREL_SYS_GET_FW_UPDATE                0x430D
#define MGMSG_PREL_SYS_SET_FW_UPDATE                0x430E
#define MGMSG_PREL_SYS_GET_HW_RICHREPSONSE          0x430F
#define MGMSG_PREL_SYS_REQ_SERIAL_NUMBER            0x4310
#define MGMSG_PREL_SYS_GET_SERIAL_NUMBER            0x4311
#define MGMSG_PREL_SYS_SET_SERIAL_NUMBER            0x4312
#define MGMSG_PREL_SYS_REQ_CALIBRATION_TIMESTAMP    0x4313
#define MGMSG_PREL_SYS_GET_CALIBRATION_TIMESTAMP    0x4314
#define MGMSG_PREL_SYS_SET_CALIBRATION_TIMESTAMP    0x4315
#define MGMSG_PREL_SYS_REQ_PROTOCOL_VERSION         0x4316
#define MGMSG_PREL_SYS_GET_PROTOCOL_VERSION         0x4317
#define MGMSG_PREL_SYS_SET_PROTOCOL_VERSION         0x4318
#define MGMSG_PREL_SYS_REQ_PRODUCT_NAME             0x4319
#define MGMSG_PREL_SYS_GET_PRODUCT_NAME             0x431A
#define MGMSG_PREL_SYS_SET_PRODUCT_NAME             APT_DEPRECATION_ERROR("deprecated") // 0x431B
#define MGMSG_PREL_SYS_REQ_MANUFACTURER_NAME        0x431C
#define MGMSG_PREL_SYS_GET_MANUFACTURER_NAME        0x431D
#define MGMSG_PREL_SYS_SET_MANUFACTURER_NAME        APT_DEPRECATION_ERROR("deprecated") // 0x431E
#define MGMSG_PREL_SYS_REQ_SUPPORTED_COMMANDS       0x4320
#define MGMSG_PREL_SYS_GET_SUPPORTED_COMMANDS       0x4321
#define MGMSG_PREL_SYS_SET_SUPPORTED_COMMANDS       0x4322
#define MGMSG_PREL_SYS_REQ_GLOBAL_FAULT             0x4323
#define MGMSG_PREL_SYS_GET_GLOBAL_FAULT             0x4324
#define MGMSG_PREL_SYS_SET_GLOBAL_FAULT             0x4325
#define MGMSG_PREL_SYS_REQ_FEEDBACK_LASER_CONTROL   0x4326
#define MGMSG_PREL_SYS_GET_FEEDBACK_LASER_CONTROL   0x4327
#define MGMSG_PREL_SYS_SET_FEEDBACK_LASER_CONTROL   0x4328
#define MGMSG_PREL_SYS_REQ_INDICATOR_LED            0x4329
#define MGMSG_PREL_SYS_GET_INDICATOR_LED            0x432A
#define MGMSG_PREL_SYS_SET_INDICATOR_LED            0x432B
#define MGMSG_PREL_SYS_REQ_POWER_SUPPLY             0x432C
#define MGMSG_PREL_SYS_GET_POWER_SUPPLY             0x432D
#define MGMSG_PREL_SYS_SET_POWER_SUPPLY             0x432E
#define MGMSG_PREL_SYS_REQ_DATA                     0x4330
#define MGMSG_PREL_SYS_GET_DATA                     0x4331
#define MGMSG_PREL_SYS_SET_DATA                     0x4332
#define MGMSG_PREL_SYS_REQ_CAMERA_LED_CONTROL       0x4333
#define MGMSG_PREL_SYS_GET_CAMERA_LED_CONTROL       0x4334
#define MGMSG_PREL_SYS_SET_CAMERA_LED_CONTROL       0x4335
#define MGMSG_PREL_SYS_REQ_SIPM_OFFSET              0x4336
#define MGMSG_PREL_SYS_GET_SIPM_OFFSET              0x4337
#define MGMSG_PREL_SYS_SET_SIPM_OFFSET              0x4338

// LCPG Subregion (0x4350 - 0x435F)
#define MGMSG_PREL_LCPG_REQ_LENS_SETTINGS           0x4350
#define MGMSG_PREL_LCPG_GET_LENS_SETTINGS           0x4351
#define MGMSG_PREL_LCPG_SET_LENS_SETTINGS           0x4352
#define MGMSG_PREL_LCPG_REQ_FOCUS_CONFIGURATIONS    0x4353
#define MGMSG_PREL_LCPG_GET_FOCUS_CONFIGURATIONS    0x4354
#define MGMSG_PREL_LCPG_SET_FOCUS_CONFIGURATIONS    0x4355
#define MGMSG_PREL_LCPG_REQ_FOCUS_POSITION_RANGES   0x4356
#define MGMSG_PREL_LCPG_GET_FOCUS_POSITION_RANGES   0x4357
#define MGMSG_PREL_LCPG_SET_FOCUS_POSITION_RANGES   0x4358
#define MGMSG_PREL_LCPG_REQ_CONTROL                 0x4359
#define MGMSG_PREL_LCPG_GET_CONTROL                 0x435A
#define MGMSG_PREL_LCPG_SET_CONTROL                 0x435B

// GG Subregion (0x4360 - 0x436F)
#define MGMSG_PREL_GG_REQ_CONTROL                   0x4360
#define MGMSG_PREL_GG_GET_CONTROL                   0x4361
#define MGMSG_PREL_GG_SET_CONTROL                   0x4362
#define MGMSG_PREL_GG_REQ_POSITION                  0x4363
#define MGMSG_PREL_GG_GET_POSITION                  0x4364
#define MGMSG_PREL_GG_SET_POSITION                  0x4365
#define MGMSG_PREL_GG_REQ_ROTATION                  0x4366
#define MGMSG_PREL_GG_GET_ROTATION                  0x4367
#define MGMSG_PREL_GG_SET_ROTATION                  0x4368

// Resonant Subregion (0x4370 - 0x438F)
#define MGMSG_PREL_RES_REQ_CONTROL                  0x4370
#define MGMSG_PREL_RES_GET_CONTROL                  0x4371
#define MGMSG_PREL_RES_SET_CONTROL                  0x4372
#define MGMSG_PREL_RES_REQ_PHASE                    0x4373
#define MGMSG_PREL_RES_GET_PHASE                    0x4374
#define MGMSG_PREL_RES_SET_PHASE                    0x4375
#define MGMSG_PREL_RES_REQ_AMPLITUDE                0x4376
#define MGMSG_PREL_RES_GET_AMPLITUDE                0x4377
#define MGMSG_PREL_RES_SET_AMPLITUDE                0x4378
#define MGMSG_PREL_RES_REQ_FREQUENCY                0x4379
#define MGMSG_PREL_RES_GET_FREQUENCY                0x437A
#define MGMSG_PREL_RES_SET_FREQUENCY                0x437B
#define MGMSG_PREL_RES_REQ_ROTATION                 0x437C
#define MGMSG_PREL_RES_GET_ROTATION                 0x437D
#define MGMSG_PREL_RES_SET_ROTATION                 0x437E
#define MGMSG_PREL_RES_REQ_FOV_BIAS_ADJUST          0x437F
#define MGMSG_PREL_RES_GET_FOV_BIAS_ADJUST          0x4380
#define MGMSG_PREL_RES_SET_FOV_BIAS_ADJUST          0x4381
#define MGMSG_PREL_RES_REQ_MAXIMUM_AMPLITUDE        0x4382
#define MGMSG_PREL_RES_GET_MAXIMUM_AMPLITUDE        0x4383
#define MGMSG_PREL_RES_SET_MAXIMUM_AMPLITUDE        0x4384
#define MGMSG_PREL_RES_REQ_FLYBACK_MODE             0x4385
#define MGMSG_PREL_RES_GET_FLYBACK_MODE             0x4386
#define MGMSG_PREL_RES_SET_FLYBACK_MODE             0x4387


// Mini 2P Subregion (0x43A0 - 0x43AF)
#define MGMSG_MINI2P_SIPM_REQ_BIAS                  0x43A0
#define MGMSG_MINI2P_SIPM_GET_BIAS                  0x43A1
#define MGMSG_MINI2P_SIPM_SET_BIAS                  0x43A2

#define MGMSG_AVAILABLE_4                           0x43FF

#endif
