#ifndef SPI_BRIDGE_PROTOCOL_H_
#define SPI_BRIDGE_PROTOCOL_H_

#include <stdint.h>

#define RT_UPDATE_CMD_ENTER_UPDATE_MODE   0x01U
#define RT_UPDATE_CMD_ERASE_SECTOR        0x02U
#define RT_UPDATE_CMD_PROGRAM_PAGE        0x03U
#define RT_UPDATE_CMD_READ_BACK           0x04U
#define RT_UPDATE_CMD_FINALIZE_AND_REBOOT 0x05U

#define RT_UPDATE_STATUS_OK           0x00U
#define RT_UPDATE_STATUS_ERR_BAD_ADDR 0x01U
#define RT_UPDATE_STATUS_ERR_ERASE    0x02U
#define RT_UPDATE_STATUS_ERR_PROGRAM  0x03U
#define RT_UPDATE_STATUS_ERR_VERIFY   0x04U
#define RT_UPDATE_STATUS_ERR_BUSY     0x05U

#endif /* SPI_BRIDGE_PROTOCOL_H_ */
